= Starter

image:https://img.shields.io/badge/vert.x-4.5.8-purple.svg[link="https://vertx.io"]

This application was generated using http://start.vertx.io

== Building

To launch your tests:
```
./mvnw clean test
```

To package your application:
```
./mvnw clean package
```

To run your application:
```
./mvnw clean compile exec:java
```

== Help

* https://vertx.io/docs/[Vert.x Documentation]
* https://stackoverflow.com/questions/tagged/vert.x?sort=newest&pageSize=15[Vert.x Stack Overflow]
* https://groups.google.com/forum/?fromgroups#!forum/vertx[Vert.x User Group]
* https://discord.gg/6ry7aqPWXy[Vert.x Discord]
* https://gitter.im/eclipse-vertx/vertx-users[Vert.x Gitter]

== Points to concern
* config
* deploy verticals
* connect db

== run
mvn clean
mvn package

== External config
java -jar target/my-first-app-1.0-SNAPSHOT.jar \
  -conf src/main/conf/app-conf.json

# log delegate
  java -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory -jar target/mconnect-auth-1.0.0-SNAPSHOT-fat.jar -conf src/main/conf/app-conf.json

  java -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory  -Dlogback.configurationFile=file:src/main/conf/log-conf.xml  -jar target/mconnect-auth-1.0.0-SNAPSHOT-fat.jar -conf src/main/conf/app-conf.json

  