-- MySQL Script generated by MySQL Workbench
-- Mon Jul  8 09:06:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mconnect-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mconnect-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mconnect-db` DEFAULT CHARACTER SET utf8mb3 ;
USE `mconnect-db` ;

-- -----------------------------------------------------
-- Table `mconnect-db`.`ath_plotp_login_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mconnect-db`.`ath_plotp_login_session` (
  `session_id` VARCHAR(64) NOT NULL,
  `user_id` VARCHAR(64) NULL DEFAULT NULL,
  `mobile_no` VARCHAR(16) NULL DEFAULT NULL,
  `otp` VARCHAR(8) NULL DEFAULT NULL,
  `access_token_expire_on` INT NULL DEFAULT NULL,
  `access_token` TEXT NULL DEFAULT NULL,
  `refresh_token` TEXT NULL DEFAULT NULL,
  `otp_checked` TINYINT NULL DEFAULT NULL,
  `refresh_token_expire_on` INT NULL DEFAULT NULL,
  PRIMARY KEY (`session_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mconnect-db`.`ath_plotp_outq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mconnect-db`.`ath_plotp_outq` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mobile_no` VARCHAR(16) NOT NULL,
  `otp` VARCHAR(8) NOT NULL,
  `sms_text` TEXT NOT NULL,
  `is_sent` TINYINT NOT NULL DEFAULT '0',
  `sent_count` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mconnect-db`.`com_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mconnect-db`.`com_company` (
  `id` VARCHAR(68) NOT NULL,
  `company_name` VARCHAR(128) NOT NULL,
  `address` VARCHAR(320) NULL DEFAULT NULL,
  `icon_url` VARCHAR(320) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mconnect-db`.`com_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mconnect-db`.`com_employee` (
  `id` VARCHAR(64) NOT NULL,
  `emp_id` VARCHAR(48) NOT NULL,
  `emp_name` VARCHAR(255) NOT NULL,
  `mobile_no` VARCHAR(16) NOT NULL,
  `email` VARCHAR(320) NULL DEFAULT NULL,
  `position_id` INT NOT NULL,
  `company_structure_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mconnect-db`.`com_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mconnect-db`.`com_position` (
  `position_id` INT NOT NULL,
  `position_name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`position_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mconnect-db`.`com_structure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mconnect-db`.`com_structure` (
  `structure_id` INT NOT NULL,
  `structure_parent_id` INT NOT NULL,
  `structure_name` VARCHAR(128) NULL DEFAULT NULL,
  `structure_ref` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`structure_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
